routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LivreController;
use App\Http\Controllers\EmailController;
use App\Http\Controllers\LivreAdminController;
use App\Http\Controllers\CategoryAdminController;
use App\Http\Controllers\AuthorAdminController;
use App\Http\Controllers\ContactController;
use App\Models\{Livre, Category,Author};
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::get("/",[LivreController::class,'index']);
Route::get("detail/{id}",[LivreController::class,'detail']);
Route::post("add_to_cart",[LivreController::class,'addToCart']);
Route::get("cart",[LivreController::class,'cartList']); 
Route::get("removecart/{id}",[LivreController::class,'removeCart']); 
Route::get("increase/{id}",[LivreController::class,'increaseQuantite']); 
Route::get("decrease/{id}",[LivreController::class,'decreaseQuantite']); 
// Route::get('/email',[EmailController::class,'create']);
// Route::post('send.email',[EmailController::class,'sendEmail']);
//Route::post('/email', 'EmailController@sendEmail')->name('send.email');
Route::get('contact', [ContactController::class, 'create']);
Route::post('contact', [ContactController::class, 'store']);

Route::resource('livres', LivreAdminController::class);
Route::resource('categories', CategoryAdminController::class);
Route::resource('authors', AuthorAdminController::class);
Route::get('author/{slug}/livres', [LivreAdminController::class, 'index'])->name('livres.author');
Route::get('/livres/{id}/category',function ($id){return Livre::find($id)->categories;});

Route::post("/Passeorder",[LivreController::class,'Passeorder']);
Route::get("orders",[LivreController::class,'orders']);
Route::get("allorders",[LivreController::class,'allorders']);
Route::get('/status/update/{id}', [LivreController::class,'updateStatus']);

app/Models/Livre.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Livre extends Model
{
    use HasFactory;
    protected $fillable = ['name','price', 'year', 'description','gallery', 'author_id'];


public function author()
    {
    return $this->belongsTo(Author::class);
    }

public function categories()
    {
    return $this->belongsToMany(Category::class);
    }
}

app/Http/Controllers/LivreController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Cart;
use App\Models\Order;
use App\Models\{Livre, Author, Category};
use Illuminate\Database\Query\Expression;
use Session;
use Illuminate\Support\Facades\DB;
class LivreController extends Controller
{
    function index()
    {
        $data= Livre::all();
        if(session()->has('info'))
        {
            toastr()->success(session('info'));session()->forget('info');}
       return view('livre',['livres'=>$data]);
    }
    function detail(Livre $livre)
    {
        // $livre =Livre::find($id);
        // $livre->with('categories')->get();
        // $livre->with('categories')->get();
        // $author=Author::find($livre->Author_id)->name;
        // return view('detail', compact('livre', 'author'));
    }
    function addToCart(Request $req)
    {
        if($req->session()->has('user'))
        {
            if (Cart::where('livre_id', '=', $req->livre_id)
                    ->where('user_id', '=', session()->get('user')['id'])
                    ->exists()) {
                        $cart= DB::table('carts')
                        ->where('livre_id', '=', $req->livre_id)
                        ->where('user_id', '=', session()->get('user')['id'])
                        ->update(['quantite' =>new Expression('quantite + 1')]);
                        return redirect('/');  
             }
             else{
           $cart= new Cart;
           $cart->user_id=$req->session()->get('user')['id'];
           $cart->livre_id=$req->livre_id;
           $cart->quantite=1;
           $cart->save();
           return redirect('/');}

        }
        else
        {
            return redirect('/login');
        }
    }
    static function total()
    {static $total = 0;
     $userId=Session::get('user')['id'];
     $UserCart= Cart::where('user_id',$userId)->get();
     foreach($UserCart as $cart)
         {$quantite=$cart->quantite;
          $livre=Livre::find($cart->livre_id)->price; 
          $total = $total +$quantite*$livre;
         }
      
     return $total;
    }
    static function cartItem()
    {
     $userId=Session::get('user')['id'];
     return Cart::where('user_id',$userId)->sum('quantite');
    }
    function cartList()
    {
       $userId=Session::get('user')['id'];
       $livres= DB::table('carts')
        ->join('livres','carts.livre_id','=','livres.id')
        ->where('carts.user_id',$userId)
        ->select('livres.*','carts.id as carts_id','carts.quantite as carts_quantite')
        ->get();

        return view('cartlist',['livres'=>$livres]);
    }
    function removeCart($id)
    {
        Cart::destroy($id);
        return redirect('cart');
    }
    function increaseQuantite($id)
    {
        Cart::where('id',$id)->update(['quantite' =>new Expression('quantite + 1')]);
        return redirect('/cart');
    }
    function decreaseQuantite($id)
    {   $cart =Cart::find($id);
        if ($cart->quantite>1){
        Cart::where('id',$id)->update(['quantite' =>new Expression('quantite - 1')]);}
        return redirect('/cart');
    }
    // function orderNow()
    // {
    //     $userId=Session::get('user')['id'];
    //     $total= $products= DB::table('carts')
    //      ->join('products','cart.product_id','=','products.id')
    //      ->where('cart.user_id',$userId)
    //      ->sum('products.price');
 
    //      return view('ordernow',['total'=>$total]);
    // }
    function Passeorder(Request $req)
    {
         $userId=Session::get('user')['id'];
         $UserCart= Cart::where('user_id',$userId)->get();
         foreach($UserCart as $cart)
         {
             $order= new Order;
             $order->livre_id=$cart['livre_id'];
             $order->user_id=$cart['user_id'];
             $order->quantite=$cart['quantite'];
             $order->statut="en cours";
             $order->adress="pending";
             $order->save();
             Cart::where('user_id',$userId)->delete(); 
         }
         $req->input();
         $req->session()->put('info', 'la commande est bien passée.');
         return redirect('/');
    }
    function orders()
    {
        $userId=Session::get('user')['id'];
        $orders= DB::table('orders')
         ->join('livres','orders.livre_id','=','livres.id')
         ->where('orders.user_id',$userId)
         ->get();
         return view('orders',['orders'=>$orders]);
    }
    function allorders()
    {
        $orders= DB::table('orders')
         ->join('livres','orders.livre_id','=','livres.id')
         ->select('orders.*','orders.id as order_id','livres.*')
         ->get();   
         return view('allorders',['orders'=>$orders]);
    }
    public function updateStatus($id)
{   $order =Order::find($id);
  if($order->statut == "livré"){$order->statut = "en cours";}
  else{$order->statut = "livré";}
     $order->save();
     return redirect('allorders');}
    
}

resources/views/livre/create.blade.php
@extends('template')
@section('content')
<div class="card" >
<header class="card-header">

<div class="container">
    <div class="row">
      <div class="col-md-12">
          <div class="pull-left">
            <p class="card-header-name">Création d'un livre :</p>
              </div>
          <div class="pull-right">
          </div>
      </div>
    </div>  
  </div>



</header>
<div class="card-content">
<div class="content">
<form action="{{ route('livres.store') }}" method="POST" enctype="multipart/form-data">
@csrf
<div class="field ">
    <label class="label">Nom</label>
    <div class="col-md-offset-4 col-xs-4">
    <input class="input @error('name') is-danger @enderror" type="text" name="name" value="{{ old('name') }}" placeholder="Nom du livre">
    </div>
    @error('name')
    <p class="help is-danger">{{ $message }}</p>
    @enderror
    </div><br>
<div class="field">
    <label class="label">Auteur</label>
<div class="select col-md-offset-5 ">
<select name="author_id" >
@foreach($authors as $author)
<option value="{{ $author->id }}">{{ $author->name }}
</option>
@endforeach
</select>
</div>
<label class="label">Categories</label>
<div class="select is-multiple  col-md-offset-5" >
<select name="CategoriesTable[]" multiple data-width="75%">
@foreach($categories as $category)
<option value="{{ $category->id }}" {{ in_array($category->id, old('CategoriesTable') ?: []) ? 'selected' : '' }}>{{ $category->name }}</option>
@endforeach
</select>
</div> 

<div class="field">
    <div class="col-md-offset-4 col-xs-4">
        <label class="label">prix</label>
    <input class="input @error('price') is-danger @enderror" type="text" name="price" value="{{ old('price') }}" placeholder="Prix du livre">
    </div>
    @error('price')
    <p class="help is-danger">{{ $message }}</p>
    @enderror
    </div>
    <div class="field">
        
        <div class="control col-md-offset-4 col-xs-4">
            <label class="label">Année</label>
        <input class="input @error('year') is-danger @enderror" type="text" name="year" value="{{ old('year') }}" placeholder="Année de publication">
        </div>
        @error('year')
        <p class="help is-danger">{{ $message }}</p>
        @enderror
        </div> 
        <div class="field">
            
            <div class="control col-md-offset-4 col-xs-4">
                <label class="label">Description</label>
            <input class="input @error('description') is-danger @enderror" type="text" name="description" value="{{ old('description') }}" placeholder="description">
            </div>
            @error('description')
            <p class="help is-danger">{{ $message }}</p>
            @enderror
            </div> 
            <div class="field">
{{--                
                <div class="control">
                    <label class="label">Image</label>
                <input class="input @error('gallery') is-danger @enderror" type="text" name="gallery" value="{{ old('gallery') }}" placeholder="image">
                </div>
                @error('gallery')
                <p class="help is-danger">{{ $message }}</p>
                @enderror
                </div>              --}}
                <div class="control col-md-offset-4 col-xs-4">

                        <label class="label">Image </label>
                         <input type="file" name="gallery" class="form-control" placeholder="Post Title">
                        @error('gallery')
                          <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                       @enderror
                </div>
<div class="field ">
<div class="control col-md-12 col-md-offset-5 spacing_top">
<button class="button is-link">Ajouter</button>
</div>

</div>

</form>
</div>
</div>
</div>
@endsection

resources/views/livre/edit.blade.php
@extends('template')
@section('content')
<div class="card">
<header class="card-header">
<p class="card-header-title">Modification d'un livre</p>
</header>
<div class="card-content">
<div class="content">
<form action="{{ route('livres.update', $livre->id) }}"method="POST" enctype="multipart/form-data">
@csrf
@method('put')
<div class="field">
<label class="label">Nom</label>
<div class="col-md-offset-4 col-xs-4">
<input class="input @error('name') is-danger @enderror"
type="text" name="name" value="{{ old('name', $livre->name) }}"
placeholder="Titre du livre">
</div>
@error('name')
<p class="help is-danger">{{ $message }}</p>
@enderror
</div><br>
<div class="field">
    <label class="label">Auteur</label>
    <div class="select col-md-offset-5 ">
    <select name="author_id" >
        @foreach($authors as $author)        
        <option value="{{ $author->id }}" {{ $author->id ==$livre->Author_id ? 'selected' : ''}}>{{ $author->name }}</option>
        @endforeach
    </select>
    </div>
    </div><br>
<div class="field">
    <label class="label">Categories</label>
    <div class="select is-multiple  col-md-offset-5" >
    <select name="CategoriesTable[]" multiple>
    @foreach($categories as $category)
    <option value="{{ $category->id }}" {{ in_array($category->id,old('CategoriesTable') ?: $livre->categories->pluck('id')->all()) ? 'selected' : '' }}>{{$category->name }}</option>
    @endforeach
    </select>
    </div>
    </div><br>
    <div class="field">
        <label class="label">Prix</label>
        <div class="col-md-offset-4 col-xs-4">
        <input class="input" name="price"value="{{ old('price', $livre->price) }}"
        placeholder="Prix du livre">

        </div>
        @error('price')
        <p class="help is-danger">{{ $message }}</p>
        @enderror
        </div><br>
        <div class="field">
            <label class="label">Année</label>
            <div class="control col-md-offset-4 col-xs-4">
            <input class="input" name="year"value="{{ old('year', $livre->year) }}"
            placeholder="Année de publication">
 
            </div>
            @error('year')
            <p class="help is-danger">{{ $message }}</p>
            @enderror
            </div><br>
<div class="field">
<label class="label">Description</label>
<div class="control col-md-offset-4 col-xs-4">
<input class="input" name="description"value="{{ old('description', $livre->description) }}"
placeholder="Description du livre">

</div>
@error('description')
<p class="help is-danger">{{ $message }}</p>
@enderror
</div>
    <div class="control col-md-offset-4 col-xs-4">

        <label class="label">Image </label>
         <input type="file" name="gallery" class="form-control" placeholder="Post Title">
        @error('gallery')
          <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
       @enderror
</div>
<div class="field">
<div class="control">
    <div class="control col-md-12 col-md-offset-5 spacing_top">
        <button class="button is-link">Envoyer</button>
        </div>

</div>
</div>
</form>
</div>
</div>
</div>
@endsection

resources/views/livre/index.blade.php
@extends('template')
@section('css')
<style>
.card-footer {
justify-content: center;
align-items: center;
padding: 0.4em;
}
.btn-info {
margin: 0.3em;
}
select, .is-info {
margin: 0.3em;
}


</style>
@endsection
{{-- @section("nav")
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Book Store</a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
@endsection --}}
@section('content')
<div class="card">
@section('content')
<div class="card">
<header class="card-header">
<p class="card-header-title">livres</p>
{{-- <div class="select">
    <select onchange="window.location.href = this.value">
    <option value="{{ route('livres.index') }}" @unless($slug) selected
    @endunless>Toutes catégories</option>
    @foreach($categories as $category)
    <option value="{{ route('livres.category', $category->slug) }}"
    {{ $slug == $category->slug ? 'selected' : '' }}>{{ $category->name }}</option>
    @endforeach
    </select>
    </div> --}}
    
<a class="btn btn-info" href="{{ route('livres.create') }}">Créer un livre</a>
{{-- <a class="btn btn-info" href="{{ route('categories.index') }}">Categories</a>
<a class="btn btn-info" href="{{ route('actors.index') }}">Acteurs</a> --}}
</header>
<div class="card-content">
<div class="content">
<table class="table is-hoverable">
<thead>
<tr>
<th>Titre</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
    @foreach($livres as $livre)
    {{-- <tr @if($livre->deleted_at) class="has-background-grey-lighter" @endif> --}}
    <td><strong>{{ $livre->name }}</strong></td>
    <td>
    {{-- @if($livre->deleted_at)
    <form action="{{ route('livres.restore', $livre->id) }}"
    method="post">
    @csrf
    @method('PUT')
    <button class="btn btn-primary"
    type="submit">Restaurer</button>
    </form>
    @else --}}
    <a class="btn btn-primary" href="{{ route('livres.show',$livre->id) }}">Voir</a>
    {{-- @endif --}}
    </td>
    <td>
    {{-- @if($livre->deleted_at)
    @else --}}
    <a class="btn btn-warning" href="{{ route('livres.edit',
    $livre->id) }}">Modifier</a>
    {{-- @endif --}}
    </td>
    <td>
        <form action="{{
            route('livres.destroy', $livre->id) }}" method="post">
            @csrf
            @method('DELETE')
            <button
            class="button is-danger" type="submit">Supprimer</button>
            </form>
            
    </td>
    </tr>
    @endforeach
    
</tbody>
</table>
</div>
</div>
</div>
@endsection

resources/views/livre/show.blade.php
@extends('template')
@section("content")
<section class="hero is-fullheight is-default is-bold">
    <div class="hero-head">
        <div class="container has-text-centered">
            <div class="columns is-vcentered">
                <div class="column is-5">
                    <figure class="image is-4by5">
                        <img src="{{ asset('storage/images/' . $livre->gallery) }}">
                    </figure>
                </div>
                <div class="column is-6 is-offset-1">
                    <h1 class="title is-2">
                        {{$livre['name']}}
                    </h1>
                    <h3 class="subtitle is-4">Prix : {{$livre['price']}} DT</h3>
                    <h4 class="subtitle is-4">Année: {{$livre['year']}}</h4>
                    <h4 class="subtitle is-4">Description: {{$livre['description']}}</h4>
                    <h4 class="subtitle is-4">Auteur: {{$author}}</h4>
                    <h3 class="subtitle is-4">Categories :</h3>
                        @foreach($livre->categories as $category)
                        <h4 class="subtitle is-4">+{{ $category->name }}</h4>
                        @endforeach
                    <br>
                     @if(Session::has('user')) 
                        @if (session('user')->role =="")
                            <p class="has-text-centered">
                                <form action="/add_to_cart" method="POST">
                                    @csrf
                                    <input type="hidden" name="livre_id" value={{$livre['id']}}>
                                <button class="button is-medium is-info is-outlined">Add to Cart</button>
                                </form>
                            </p>
                        @endif
                    @else
                    <p class="has-text-centered">
                        <form action="/add_to_cart" method="POST">
                            @csrf
                            <input type="hidden" name="livre_id" value={{$livre['id']}}>
                        <button class="button is-medium is-info is-outlined">Add to Cart</button>
                        </form>
                    </p>
                @endif 
                </div>
            </div>
        </div>
    </div>
</section>
@endsection