routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LivreController;
use App\Http\Controllers\EmailController;
use App\Http\Controllers\LivreAdminController;
use App\Http\Controllers\CategoryAdminController;
use App\Http\Controllers\AuthorAdminController;
use App\Http\Controllers\ContactController;
use App\Models\{Livre, Category,Author};
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::get("/",[LivreController::class,'index']);
Route::get("detail/{id}",[LivreController::class,'detail']);
Route::post("add_to_cart",[LivreController::class,'addToCart']);
Route::get("cart",[LivreController::class,'cartList']); 
Route::get("removecart/{id}",[LivreController::class,'removeCart']); 
Route::get("increase/{id}",[LivreController::class,'increaseQuantite']); 
Route::get("decrease/{id}",[LivreController::class,'decreaseQuantite']); 
// Route::get('/email',[EmailController::class,'create']);
// Route::post('send.email',[EmailController::class,'sendEmail']);
//Route::post('/email', 'EmailController@sendEmail')->name('send.email');
Route::get('contact', [ContactController::class, 'create']);
Route::post('contact', [ContactController::class, 'store']);

Route::resource('livres', LivreAdminController::class);
Route::resource('categories', CategoryAdminController::class);
Route::resource('authors', AuthorAdminController::class);
Route::get('author/{slug}/livres', [LivreAdminController::class, 'index'])->name('livres.author');
Route::get('/livres/{id}/category',function ($id){return Livre::find($id)->categories;});

Route::post("/Passeorder",[LivreController::class,'Passeorder']);
Route::get("orders",[LivreController::class,'orders']);
Route::get("allorders",[LivreController::class,'allorders']);
Route::get('/status/update/{id}', [LivreController::class,'updateStatus']);

app/Models/Author.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'slug'];

public function livres()
    {
    return $this->hasMany(Livre::class);
    }
}

resources/views/author/create.blade.php
@extends('template')
@section('content')
<div class="card">
<header class="card-header">
<p class="card-header-title">Création d'une auteur</p>
</header>
<div class="card-content">
<div class="content">
<form action="{{ route('authors.store') }}" method="POST">
@csrf
<div class="field">
<label class="label">Name</label>
<div class="control">
<input class="input @error('name') is-danger @enderror" type="text" name="name" value="{{ old('name') }}" placeholder="nom du auteur">
</div>
@error('name')
<p class="help is-danger">{{ $message }}</p>
@enderror
</div>
<div class="field">
    <label class="label">Slug</label>
    <div class="control">
    <input class="input @error('slug') is-danger @enderror" type="text" name="slug" value="{{ old('slug') }}" placeholder="Slug du auteur">
    </div>
    @error('slug')
    <p class="help is-danger">{{ $message }}</p>
    @enderror
    </div>
<div class="field">
<div class="control">
<button class="button is-link">Envoyer</button>
</div>
</div>
</form>
</div>
</div>
</div>
@endsection

resources/views/author/edit.blade.php
@extends('template')
@section('content')
<div class="card">
<header class="card-header">
<p class="card-header-title">Modification d'une auteur</p>
</header>
<div class="card-content">
<div class="content">
<form action="{{ route('authors.update', $author->id) }}"
method="POST">
@csrf
@method('put')
<div class="field">
<label class="label">Nom</label>
<div class="control">
<input class="input @error('name') is-danger @enderror"
type="text" name="name" value="{{ old('name', $author->name) }}"
placeholder="Nom du auteur">
</div>
@error('name')
<p class="help is-danger">{{ $message }}</p>
@enderror
</div>

<div class="field">
<label class="label">slug</label>
<div class="control">
<textarea class="textarea" name="slug"
placeholder="slug">{{ old('slug', $author->slug) }}
</textarea>
</div>
@error('slug')
<p class="help is-danger">{{ $message }}</p>
@enderror
</div>
<div class="field">
<div class="control">
<button class="button is-link">Envoyer</button>
</div>
</div>
</form>
</div>
</div>
</div>
@endsection

resources/views/author/index.blade.php
@extends('template')
@section('css')
<style>
.card-footer {
justify-content: center;
align-items: center;
padding: 0.4em;
}
.btn-info {
margin: 0.3em;
}
</style>
@endsection
@section('content')
@if(session()->has('info'))
<div class="alert alert-success">
{{ session('info') }}
</div>
@endif
<div class="card">
@section('content')
<div class="card">
<header class="card-header">
<p class="card-header-title">Auteurs</p>
<a class="btn btn-info" href="{{ route('authors.create') }}">Ajouter une Auteur</a>
</header>
<div class="card-content">
<div class="content">
<table class="table is-hoverable">
<thead>
<tr>
<th>Name</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
    @foreach($authors as $author)
<tr>
<td><strong>{{ $author->name}}</strong></td>
<td><a class="btn btn-primary" href="{{ route('authors.show', $author->id)}}">Voir</a></td>
<td><a class="btn btn-warning" href="{{ route('authors.edit', $author->id)}}">Modifier</a></td>
<td>
<form action="{{route('authors.destroy', $author->id) }}" method="post">
@csrf
@method('DELETE')
<button class="btn btn-danger" type="submit">Supprimer</button>
</form>
</td>
</tr>
@endforeach

    
</tbody>
</table>
</div>
</div>
</div>
@endsection

resources/views/author/show.blade.php
@extends('template')
@section('content')
<div class="card">
<header class="card-header">
<p class="card-header-title">Name : {{ $author->name }}</p>
</header>
<div class="card-content">
<div class="content">
<p>Slug : {{ $author->slug }}</p>
</div>
</div>
</div>
@endsection